Repository FrontHeads/tanchiki, pull requests merged in 2022-12, with the labels that each got.

#32 Add project description
  README.md
  docs/lerna/README.md
Labels: documentation

#36 Add fullscreen(WebAPI)
  packages/client/src/game/services/Game.ts
  packages/client/src/game/services/KeyBindings.ts
  packages/client/src/game/services/View.ts
  packages/client/src/pages/Game/Game.css
Labels: enhancement

#37 Fix "game over" animation
  packages/client/src/game/services/Game.ts
Labels: bug

#41 Add Error Boundary
  packages/client/src/components/ErrorBody/ErrorBody.tsx
  packages/client/src/components/ErrorBody/index.ts
  packages/client/src/components/ErrorBody/typings.ts
  packages/client/src/components/ErrorBoundary/ErrorBoundary.tsx
  packages/client/src/components/ErrorBoundary/index.ts
  packages/client/src/components/ErrorBoundary/typings.ts
  packages/client/src/config/router.tsx
  packages/client/src/layouts/Root/Root.tsx
  packages/client/src/pages/ErrorPage/ErrorPage.tsx
  packages/client/src/pages/SignIn/SignIn.tsx
Labels: enhancement

#42 Add AudioManager class
  packages/client/src/game/entities/EntityDynamic.ts
  packages/client/src/game/entities/Tank.ts
  packages/client/src/game/services/AudioManager.test.ts
  packages/client/src/game/services/AudioManager.ts
  packages/client/src/game/services/Game.ts
  packages/client/src/game/services/Resources/Resources.ts
  packages/client/src/game/services/Resources/data.ts
Labels: enhancement

#43 Update game scenario
  packages/client/src/game/entities/Entity.ts
  packages/client/src/game/services/Game.ts
  packages/client/src/game/services/MapManager.ts
  packages/client/src/game/services/Scenario.ts
  packages/client/src/game/typings/index.ts
  packages/client/src/game/ui/screens/LevelSelectorScreen.ts
  packages/client/src/game/utils/EventEmitter.ts
Labels: enhancement

#44 Add graphics
  packages/client/src/config/router.tsx
  packages/client/src/game/data/constants.ts
  packages/client/src/game/data/spriteCoordinates.ts
  packages/client/src/game/entities/Entity.test.ts
  packages/client/src/game/entities/Entity.ts
  packages/client/src/game/entities/EntityDynamic.ts
  packages/client/src/game/entities/Explosion.test.ts
  packages/client/src/game/entities/Explosion.ts
  packages/client/src/game/entities/Flag.ts
  packages/client/src/game/entities/Projectile.ts
  packages/client/src/game/entities/Tank.test.ts
  packages/client/src/game/entities/Tank.ts
  packages/client/src/game/entities/TankEnemy.ts
  packages/client/src/game/entities/Terrain.ts
  packages/client/src/game/entities/index.ts
  packages/client/src/game/services/AudioManager.test.ts
  packages/client/src/game/services/AudioManager.ts
  packages/client/src/game/services/Controller.test.ts
  packages/client/src/game/services/Game.ts
  packages/client/src/game/services/KeyBindings.ts
  packages/client/src/game/services/Resources/data.ts
  packages/client/src/game/services/Scenario.test.ts
  packages/client/src/game/services/Scenario.ts
  packages/client/src/game/services/View.test.ts
  packages/client/src/game/services/View.ts
  packages/client/src/game/services/Zone.ts
  packages/client/src/game/typings/index.ts
  packages/client/src/game/ui/Overlay.test.ts
  packages/client/src/game/ui/Overlay.ts
  packages/client/src/game/ui/UIElement.ts
  packages/client/src/game/ui/screens/MainMenuScreen.ts
  packages/client/src/game/ui/screens/Screen.test.ts
  packages/client/src/game/utils/sleepTimer.ts
Labels: enhancement

#45 refactor(General): replace all "&&" to ternary operators
  packages/client/src/components/Form/FieldList/Field/Field.tsx
  packages/client/src/components/Form/Form.tsx
  packages/client/src/layouts/Root/Root.tsx
Labels: refactor

#48 Update entity and controller event typings
  packages/client/src/game/entities/Entity.test.ts
  packages/client/src/game/entities/Entity.ts
  packages/client/src/game/entities/EntityDynamic.ts
  packages/client/src/game/entities/Explosion.ts
  packages/client/src/game/entities/Flag.ts
  packages/client/src/game/entities/Tank.test.ts
  packages/client/src/game/entities/Tank.ts
  packages/client/src/game/entities/TankEnemy.ts
  packages/client/src/game/entities/Terrain.ts
  packages/client/src/game/services/AudioManager.ts
  packages/client/src/game/services/Controller.test.ts
  packages/client/src/game/services/Controller.ts
  packages/client/src/game/services/Game.ts
  packages/client/src/game/services/KeyBindings.ts
  packages/client/src/game/services/Scenario.ts
  packages/client/src/game/services/View.test.ts
  packages/client/src/game/services/View.ts
  packages/client/src/game/services/Zone.test.ts
  packages/client/src/game/services/Zone.ts
  packages/client/src/game/typings/index.ts
  packages/client/src/game/ui/UIElement.test.ts
  packages/client/src/game/ui/UIElement.ts
  packages/client/src/game/utils/EventEmitter.ts
Labels: refactor

#47 Fix shooting bug
  packages/client/src/game/services/Scenario.ts
Labels: bug

#46 Add background to "Game over" screen
  packages/client/src/game/services/Game.ts
  packages/client/src/game/services/Scenario.ts
  packages/client/src/game/typings/index.ts
  packages/client/src/game/ui/Overlay.ts
  packages/client/src/game/ui/screens/GameOverScreen.ts
  packages/client/src/game/ui/screens/LevelSelectorScreen.ts
  packages/client/src/game/ui/screens/LevelSelectorScreen.typings.ts
Labels: enhancement

#55 Add service worker
  packages/client/.stylelintignore
  packages/client/.stylelintrc.json
  packages/client/package.json
  packages/client/src/game/entities/Explosion.ts
  packages/client/src/main.tsx
  packages/client/src/serviceWorker.ts
  packages/client/src/utils/serviceWorkerUtils.ts
  packages/client/tsconfig.json
  packages/client/vite.config.ts
Labels: enhancement

#53 Add form validation
  packages/client/src/components/BurgerMenu/BurgerMenu.css
  packages/client/src/components/Form/FieldList/Field/Field.tsx
  packages/client/src/components/Form/FieldList/Field/typings.tsx
  packages/client/src/components/Form/FieldList/FieldList.test.tsx
  packages/client/src/components/Form/FieldList/FieldList.tsx
  packages/client/src/components/Form/FieldList/typings.ts
  packages/client/src/components/Form/Form.css
  packages/client/src/components/Form/Form.test.tsx
  packages/client/src/components/Form/Form.tsx
  packages/client/src/components/Form/typings.tsx
  packages/client/src/components/ValidationErrors/ValidationErrors.css
  packages/client/src/components/ValidationErrors/ValidationErrors.test.tsx
  packages/client/src/components/ValidationErrors/ValidationErrors.tsx
  packages/client/src/components/ValidationErrors/index.ts
  packages/client/src/components/ValidationErrors/typings.ts
  packages/client/src/index.css
  packages/client/src/pages/Forum/ForumTopic/ForumTopic.css
  packages/client/src/pages/Forum/ForumTopic/ForumTopic.tsx
  packages/client/src/pages/SignIn/SignIn.tsx
  packages/client/src/pages/SignIn/data.ts
  packages/client/src/pages/SignUp/SignUp.tsx
  packages/client/src/pages/SignUp/data.ts
  packages/client/src/pages/UserProfile/UserProfile.tsx
  packages/client/src/pages/UserProfile/data.ts
  packages/client/src/utils/validation/config.ts
  packages/client/src/utils/validation/index.ts
  packages/client/src/utils/validation/typings.ts
  packages/client/src/utils/validation/validation.ts
  packages/client/src/utils/validation/validators.ts
  packages/client/src/variables.css
Labels: enhancement

#60 Adjust game entity movement
  packages/client/src/game/data/constants.ts
  packages/client/src/game/entities/EntityDynamic.ts
  packages/client/src/game/entities/Explosion.ts
  packages/client/src/game/entities/Projectile.ts
  packages/client/src/game/entities/Tank.test.ts
  packages/client/src/game/entities/Tank.ts
  packages/client/src/game/entities/TankEnemy.ts
  packages/client/src/game/entities/TankPlayer.test.ts
  packages/client/src/game/entities/TankPlayer.ts
  packages/client/src/game/entities/index.ts
  packages/client/src/game/services/AudioManager.ts
  packages/client/src/game/services/Loop.test.ts
  packages/client/src/game/services/Loop.ts
  packages/client/src/game/services/Scenario.ts
  packages/client/src/game/services/View.test.ts
  packages/client/src/game/services/View.ts
  packages/client/src/game/services/Zone.ts
  packages/client/src/game/typings/index.ts
  packages/client/src/serviceWorker.ts
Labels: bug, refactor
