Repository FrontHeads/tanchiki, pull requests merged in 2023-02, with the labels that each got.

#87 Add game powerups
  packages/client/src/game/entities/Entity/Entity.ts
  packages/client/src/game/entities/Powerup/Powerup.test.ts
  packages/client/src/game/entities/Powerup/Powerup.ts
  packages/client/src/game/entities/Powerup/typings.ts
  packages/client/src/game/entities/Projectile/Projectile.ts
  packages/client/src/game/entities/Projectile/typings.ts
  packages/client/src/game/entities/Score/Score.ts
  packages/client/src/game/entities/Tank/Tank.ts
  packages/client/src/game/entities/Tank/TankEnemy.ts
  packages/client/src/game/entities/Tank/TankPlayer.ts
  packages/client/src/game/entities/Tank/typings.ts
  packages/client/src/game/entities/index.ts
  packages/client/src/game/services/AudioManager/AudioManager.ts
  packages/client/src/game/services/Game/Game.ts
  packages/client/src/game/services/MapManager/MapManager.ts
  packages/client/src/game/services/Resources/data.ts
  packages/client/src/game/services/Scenario/Scenario.ts
  packages/client/src/game/services/Scenario/typings.ts
  packages/client/src/game/services/Statistics/Statistics.ts
  packages/client/src/game/services/View/View.ts
  packages/client/src/game/services/View/spriteCoordinates.ts
  packages/client/src/game/services/Zone/Zone.ts
Labels: enhancement

#85 SSR user authentication
  packages/client/package.json
  packages/client/src/components/ThemeToggle/ThemeToggle.tsx
  packages/client/src/config/leaderboardRoute.tsx
  packages/client/src/config/router.tsx
  packages/client/src/layouts/Root/Root.tsx
  packages/client/src/pages/Leaderboard/Leaderboard.test.tsx
  packages/client/src/pages/Leaderboard/Leaderboard.tsx
  packages/client/src/pages/Leaderboard/LeaderboardRow/LeaderboardRow.tsx
  packages/client/src/store/features/leaderboard/leaderboardSlice.ts
  packages/client/src/tests/data.ts
  packages/client/src/tests/setup.ts
  packages/client/src/utils/HTTP/HTTP.test.tsx
  packages/client/src/utils/HTTP/HTTP.tsx
  packages/client/src/utils/HTTP/httpClient.ts
  packages/client/src/utils/HTTP/index.tsx
  packages/client/src/utils/testingUtils.tsx
  packages/client/ssr.tsx
  packages/server/index.ts
  packages/server/middlewares/index.ts
  packages/server/middlewares/requestDataSaver.ts
  packages/server/package.json
  packages/server/routes/SSR.ts
  packages/server/utils/isDev.ts
  yarn.lock
Labels: enhancement

#88 Pointer control
  packages/client/src/components/BurgerMenu/BurgerMenu.css
  packages/client/src/game/entities/Explosion/Explosion.test.ts
  packages/client/src/game/services/Controller/Controller.test.ts
  packages/client/src/game/services/Controller/ControllerBase.ts
  packages/client/src/game/services/Controller/ControllerDesktop.ts
  packages/client/src/game/services/Controller/ControllerPointer.ts
  packages/client/src/game/services/Controller/KeyBindings.ts
  packages/client/src/game/services/Controller/data.ts
  packages/client/src/game/services/Controller/typings.ts
  packages/client/src/game/services/Game/Game.ts
  packages/client/src/game/services/Resources/Resources.ts
  packages/client/src/game/services/Scenario/Scenario.ts
  packages/client/src/game/services/Scenario/typings.ts
  packages/client/src/game/services/View/View.test.ts
  packages/client/src/game/services/View/View.ts
  packages/client/src/game/services/View/data.ts
  packages/client/src/game/services/View/spriteCoordinates.ts
  packages/client/src/game/services/index.ts
  packages/client/src/game/ui/Overlay/Overlay.ts
  packages/client/src/game/ui/screens/GameScreens/LevelSelectorScreen.ts
  packages/client/src/game/ui/screens/UIScreens/MainMenuScreen.ts
  packages/client/src/game/utils/isTouchscreen.ts
  packages/client/src/layouts/Root/Root.css
  packages/client/src/pages/Game/Game.css
  packages/client/src/pages/Game/Game.tsx
  packages/client/src/pages/Game/PointerControl/Buttons/Buttons.css
  packages/client/src/pages/Game/PointerControl/Buttons/Buttons.test.tsx
  packages/client/src/pages/Game/PointerControl/Buttons/Buttons.tsx
  packages/client/src/pages/Game/PointerControl/Buttons/SVGImages.tsx
  packages/client/src/pages/Game/PointerControl/Joystick/Joystick.css
  packages/client/src/pages/Game/PointerControl/Joystick/Joystick.test.tsx
  packages/client/src/pages/Game/PointerControl/Joystick/Joystick.tsx
  packages/client/src/pages/Game/PointerControl/controller.css
  packages/client/src/pages/Game/PointerControl/index.tsx
  packages/client/src/pages/Game/typings.ts
  packages/client/src/pages/Home/Home.css
  packages/client/src/variables.css
Labels: enhancement

#92 Project deployment
  .dockerignore
  .env.sample
  .github/workflows/deploy.yml
  Dockerfile.server
  README.md
  docker-compose.dev.yml
  docker-compose.prod.yml
  docker-compose.yml
  package.json
  packages/client/jest.config.js
  packages/client/src/api/contactAPI.ts
  packages/client/src/client.d.ts
  packages/client/src/config/constants.tsx
  packages/client/src/pages/Contact/Contact.tsx
  packages/client/src/tests/setup.ts
  packages/client/src/utils/HTTP/HTTP.test.tsx
  packages/client/src/utils/HTTP/determineAPIHost.ts
  packages/client/ssr.config.ts
  packages/client/vite.config.ts
  packages/server/config/constants.ts
  packages/server/middlewares/proxy.ts
Labels: enhancement

#93 Protect forum from XSS
  packages/client/src/pages/Forum/ForumSection/ForumNewTopic/ForumNewTopic.tsx
  packages/client/src/pages/Forum/ForumTopic/ForumMessage/ForumMessage.tsx
  packages/client/src/pages/Forum/ForumTopic/ForumTopic.tsx
  packages/client/src/pages/Forum/ForumTopic/ForumTopicDescription/ForumTopicDescription.tsx
  packages/client/src/utils/validation/config.ts
  packages/client/src/utils/validation/validators.ts
  packages/server/api/services/ForumMessage.ts
  packages/server/api/services/ForumTopic.ts
  packages/server/api/services/Themization.ts
  packages/server/middlewares/xssValidation.ts
  packages/server/package.json
Labels: bug

#91 Refactor game state
  docs/gameEngine.md
  packages/client/src/game/entities/Explosion/Explosion.test.ts
  packages/client/src/game/entities/Powerup/Powerup.test.ts
  packages/client/src/game/entities/Projectile/Projectile.test.ts
  packages/client/src/game/entities/Tank/Tank.test.ts
  packages/client/src/game/entities/Tank/TankPlayer.ts
  packages/client/src/game/entities/Tank/typings.ts
  packages/client/src/game/entities/index.ts
  packages/client/src/game/services/AudioManager/AudioManager.test.ts
  packages/client/src/game/services/AudioManager/AudioManager.ts
  packages/client/src/game/services/Controller/ControllerBase.ts
  packages/client/src/game/services/Game/Game.ts
  packages/client/src/game/services/Game/typings.ts
  packages/client/src/game/services/IndicatorManager/IndicatorManager.test.ts
  packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
  packages/client/src/game/services/MapManager/MapManager.ts
  packages/client/src/game/services/Resources/Resources.test.ts
  packages/client/src/game/services/Resources/Resources.ts
  packages/client/src/game/services/Resources/data.ts
  packages/client/src/game/services/Scenario/Scenario.test.ts
  packages/client/src/game/services/Scenario/Scenario.ts
  packages/client/src/game/services/Scenario/data.ts
  packages/client/src/game/services/Scenario/typings.ts
  packages/client/src/game/services/State/State.ts
  packages/client/src/game/services/Statistics/Statistics.test.ts
  packages/client/src/game/services/View/View.test.ts
  packages/client/src/game/services/View/View.ts
  packages/client/src/game/services/Zone/Zone.test.ts
  packages/client/src/game/services/Zone/Zone.ts
  packages/client/src/game/services/index.ts
  packages/client/src/game/ui/screens/GameScreens/PausePopupScreen.ts
  packages/client/src/game/ui/screens/UIScreens/MainMenuScreen.ts
  packages/client/src/pages/Game/Game.tsx
Labels: refactor

#90 Minor fix typings
  packages/client/src/api/authAPI.ts
  packages/client/src/api/authAPI/authAPI.ts
  packages/client/src/api/authAPI/index.ts
  packages/client/src/api/authAPI/typings.ts
  packages/client/src/api/contactAPI/contactAPI.ts
  packages/client/src/api/contactAPI/index.ts
  packages/client/src/api/contactAPI/typings.ts
  packages/client/src/api/forumAPI.ts
  packages/client/src/api/forumAPI/forumAPI.ts
  packages/client/src/api/forumAPI/index.ts
  packages/client/src/api/forumAPI/typings.ts
  packages/client/src/api/leaderboardAPI/index.ts
  packages/client/src/api/leaderboardAPI/leaderboardAPI.ts
  packages/client/src/api/leaderboardAPI/typings.ts
  packages/client/src/api/oauthAPI.ts
  packages/client/src/api/oauthAPI/index.ts
  packages/client/src/api/oauthAPI/oauthAPI.ts
  packages/client/src/api/oauthAPI/typings.ts
  packages/client/src/api/themizationAPI/index.ts
  packages/client/src/api/themizationAPI/themizationAPI.ts
  packages/client/src/api/themizationAPI/typings.ts
  packages/client/src/api/userAPI.ts
  packages/client/src/api/userAPI/index.ts
  packages/client/src/api/userAPI/typings.ts
  packages/client/src/api/userAPI/userAPI.ts
  packages/client/src/app.typings.ts
  packages/client/src/game/services/View/View.ts
  packages/client/src/game/services/View/typings.ts
  packages/client/src/layouts/Root/Root.tsx
  packages/client/src/pages/Leaderboard/Leaderboard.tsx
  packages/client/src/pages/Leaderboard/LeaderboardRow/typings.ts
  packages/client/src/store/features/leaderboard/leaderboardSlice.ts
  packages/client/src/store/features/leaderboard/leaderboardThunks.ts
  packages/client/src/store/features/leaderboard/typings.ts
  packages/client/src/tests/data.ts
  packages/client/src/utils/HTTP/httpClient.ts
  packages/client/src/utils/apiUtils.ts
  packages/server/tsconfig.json
Labels: refactor

#89 Content Security Policy
  packages/client/ssr.tsx
  packages/server/config/constants.ts
  packages/server/config/cspDirectives.ts
  packages/server/index.ts
  packages/server/package.json
  packages/server/routes/SSR.ts
  packages/server/tsconfig.json
  packages/server/types/index.d.ts
  packages/server/utils/expressCspHeader.ts
  yarn.lock
Labels: enhancement

#95 Add Web Audio API
  packages/client/src/client.d.ts
  packages/client/src/game/services/AudioManager/AudioManager.test.ts
  packages/client/src/game/services/AudioManager/AudioManager.ts
  packages/client/src/game/services/AudioManager/typings.ts
  packages/client/src/game/services/Resources/Resources.test.ts
  packages/client/src/game/services/Resources/Resources.ts
  packages/client/src/game/services/Resources/typings.ts
  packages/client/src/tests/setup.ts
Labels: bug

#96 Fix game bugs
  README.md
  docs/gameEngine.md
  package.json
  packages/client/src/game/services/Debug/Debug.ts
  packages/client/src/game/services/Game/Game.ts
  packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
  packages/client/src/game/services/Scenario/Scenario.ts
  packages/client/src/game/services/State/State.ts
  packages/client/src/game/services/Statistics/Statistics.test.ts
  packages/client/src/game/services/index.ts
Labels: bug

#97 Implement concrete walls destruction
  packages/client/src/game/entities/Entity/Entity.ts
  packages/client/src/game/entities/Terrain/Terrain.test.ts
  packages/client/src/game/entities/Terrain/Terrain.ts
  packages/client/src/game/entities/index.ts
  packages/client/src/game/services/State/State.ts
  packages/client/src/game/services/View/View.ts
  packages/client/src/game/services/Zone/Zone.ts
Labels: enhancement

#98 Fix SSR issues
  .github/workflows/deploy.yml
  README.md
  packages/client/src/components/BurgerMenu/BurgerMenu.css
  packages/client/src/components/BurgerMenu/BurgerMenu.test.tsx
  packages/client/src/components/MenuLink/typings.ts
  packages/client/src/components/Navigation/Navigation.tsx
  packages/client/src/config/leaderboardRoute.tsx
  packages/client/src/config/router.tsx
  packages/client/src/layouts/Root/Root.tsx
  packages/client/src/main.tsx
  packages/client/src/pages/Forum/ForumSection/ForumSection.test.tsx
  packages/client/src/pages/Forum/ForumTopic/ForumTopic.test.tsx
  packages/client/src/pages/Leaderboard/Leaderboard.test.tsx
  packages/client/src/pages/Leaderboard/Leaderboard.tsx
  packages/client/src/pages/Leaderboard/LeaderboardRow/LeaderboardRow.tsx
  packages/client/src/serviceWorker.ts
  packages/client/src/store/features/app/app.test.ts
  packages/client/src/store/features/auth/auth.test.ts
  packages/client/src/store/features/auth/authSlice.ts
  packages/client/src/store/features/auth/authThunks.ts
  packages/client/src/store/features/leaderboard/leaderboardSlice.ts
  packages/client/src/store/features/profile/profile.test.ts
  packages/client/src/store/index.ts
  packages/client/src/store/store.ts
  packages/client/src/tests/TestApp.tsx
  packages/client/src/utils/testingUtils.tsx
  packages/client/ssr.tsx
  packages/server/index.ts
  packages/server/routes/SSR.ts
Labels: bug

#99 Improve form library
  packages/client/src/app.typings.ts
  packages/client/src/components/Form/FieldList/Field/Field.tsx
  packages/client/src/components/Form/FieldList/Field/typings.tsx
  packages/client/src/components/Form/FieldList/FieldList.test.tsx
  packages/client/src/components/Form/FieldList/FieldList.tsx
  packages/client/src/components/Form/FieldList/typings.ts
  packages/client/src/components/Form/Form.css
  packages/client/src/components/Form/Form.test.tsx
  packages/client/src/components/Form/Form.tsx
  packages/client/src/components/Form/FormContext.tsx
  packages/client/src/components/Form/typings.tsx
  packages/client/src/components/ValidationErrors/ValidationErrors.css
  packages/client/src/index.css
  packages/client/src/pages/Contact/Contact.tsx
  packages/client/src/pages/SignIn/SignIn.tsx
  packages/client/src/pages/SignUp/SignUp.tsx
  packages/client/src/pages/UserProfile/UserProfile.tsx
  packages/client/src/pages/UserProfile/data.ts
  packages/client/src/utils/validation/config.ts
Labels: enhancement

#101 Add game difficulty
  packages/client/src/game/entities/Tank/TankEnemy.ts
  packages/client/src/game/entities/Tank/typings.ts
  packages/client/src/game/services/Game/Game.ts
  packages/client/src/game/services/Game/data.ts
  packages/client/src/game/services/Scenario/Scenario.ts
  packages/client/src/game/services/State/State.ts
  packages/client/src/game/services/Statistics/Statistics.test.ts
  packages/client/src/game/services/Statistics/Statistics.ts
  packages/client/src/game/services/index.ts
  packages/client/src/game/ui/screens/GameScreens/ScoreScreen.ts
  packages/client/src/game/ui/screens/UIScreens/MainMenuScreen.ts
  packages/client/src/game/ui/screens/UIScreens/data.ts
Labels: enhancement
