Repository FrontHeads/tanchiki, pull requests merged in 2023-01, with the labels that each got.

#61 Add ice and sliding mechanics
  packages/client/src/game/data/constants.ts
  packages/client/src/game/entities/EntityDynamic.ts
  packages/client/src/game/entities/Tank.test.ts
  packages/client/src/game/entities/Tank.ts
  packages/client/src/game/entities/TankEnemy.ts
  packages/client/src/game/entities/TankPlayer.ts
  packages/client/src/game/entities/Terrain.ts
  packages/client/src/game/services/AudioManager.ts
  packages/client/src/game/services/Game.ts
  packages/client/src/game/services/Resources/data.ts
  packages/client/src/game/services/View.ts
  packages/client/src/game/services/Zone.test.ts
  packages/client/src/game/services/Zone.ts
  packages/client/src/game/typings/index.ts
Labels: bug, enhancement

#62 Add indicators bar
  .github/workflows/checks.yml
  package.json
  packages/client/package.json
  packages/client/src/client.d.ts
  packages/client/src/game/data/colors.ts
  packages/client/src/game/data/constants.ts
  packages/client/src/game/entities/Entity.ts
  packages/client/src/game/entities/Explosion.ts
  packages/client/src/game/entities/Flag.ts
  packages/client/src/game/entities/Projectile.ts
  packages/client/src/game/entities/Tank.ts
  packages/client/src/game/entities/TankEnemy.ts
  packages/client/src/game/entities/Terrain.ts
  packages/client/src/game/services/Game.ts
  packages/client/src/game/services/IndicatorManager/IndicatorManager.test.ts
  packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
  packages/client/src/game/services/IndicatorManager/data.ts
  packages/client/src/game/services/Resources/Resources.test.ts
  packages/client/src/game/services/Scenario.ts
  packages/client/src/game/services/View.test.ts
  packages/client/src/game/services/View.ts
  packages/client/src/game/services/index.ts
  packages/client/src/game/typings/index.ts
  packages/client/src/game/ui/Overlay.test.ts
  packages/client/src/game/ui/Overlay.ts
  packages/client/src/game/ui/UIElement.ts
  packages/client/src/game/ui/screens/GameOverScreen.ts
  packages/client/src/game/ui/screens/GameScreen.ts
  packages/client/src/game/ui/screens/LevelSelectorScreen.ts
  packages/client/src/game/ui/screens/LoadingScreen.ts
  packages/client/src/game/ui/screens/MainMenuScreen.ts
  packages/client/src/pages/Game/Game.css
  packages/server/package.json
  yarn.lock
Labels: enhancement

#64 Add Web API section to the readme
  README.md
Labels: documentation

#59 SSR
  README.md
  package.json
  packages/client/index.html
  packages/client/index.js
  packages/client/package.json
  packages/client/src/client.d.ts
  packages/client/src/config/router.tsx
  packages/client/src/game/services/View.ts
  packages/client/src/layouts/Root/Root.tsx
  packages/client/src/main.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/serviceWorker.ts
  packages/client/src/store/store.ts
  packages/client/ssr.config.ts
  packages/client/ssr.tsx
  packages/client/tsconfig.json
  packages/server/index.ts
  packages/server/package.json
  packages/server/tsconfig.json
  packages/server/utils/HtmlWritable.ts
  yarn.lock
Labels: enhancement

#63 Add game score
  packages/client/src/game/data/colors.ts
  packages/client/src/game/data/constants.ts
  packages/client/src/game/data/spriteCoordinates.ts
  packages/client/src/game/entities/Entity.ts
  packages/client/src/game/entities/Explosion.test.ts
  packages/client/src/game/entities/Explosion.ts
  packages/client/src/game/entities/Flag.ts
  packages/client/src/game/entities/Projectile.ts
  packages/client/src/game/entities/Score.test.ts
  packages/client/src/game/entities/Score.ts
  packages/client/src/game/entities/Tank.ts
  packages/client/src/game/entities/TankEnemy.ts
  packages/client/src/game/entities/TankPlayer.test.ts
  packages/client/src/game/entities/TankPlayer.ts
  packages/client/src/game/entities/Terrain.ts
  packages/client/src/game/entities/index.ts
  packages/client/src/game/services/AudioManager.ts
  packages/client/src/game/services/Controller.ts
  packages/client/src/game/services/Game.ts
  packages/client/src/game/services/IndicatorManager/data.ts
  packages/client/src/game/services/KeyBindings.ts
  packages/client/src/game/services/Resources/data.ts
  packages/client/src/game/services/Scenario.ts
  packages/client/src/game/services/Statistics.test.ts
  packages/client/src/game/services/Statistics.ts
  packages/client/src/game/services/View.ts
  packages/client/src/game/services/Zone.ts
  packages/client/src/game/services/index.ts
  packages/client/src/game/typings/index.ts
  packages/client/src/game/ui/Overlay.ts
  packages/client/src/game/ui/UIElement.ts
  packages/client/src/game/ui/screens/GameOverPopupScreen.ts
  packages/client/src/game/ui/screens/GameStartScreen.ts
  packages/client/src/game/ui/screens/MainMenuScreen.ts
  packages/client/src/game/ui/screens/PausePopupScreen.ts
  packages/client/src/game/ui/screens/ScoreScreen.ts
  packages/client/src/game/ui/screens/Screen.test.ts
  packages/client/src/game/ui/screens/index.ts
  packages/client/src/game/utils/EventEmitter.test.ts
  packages/client/src/game/utils/EventEmitter.ts
  packages/client/src/pages/Game/Game.tsx
Labels: enhancement, refactor

#58 Add leaderboard API
  .eslintrc.js
  packages/client/.stylelintignore
  packages/client/package.json
  packages/client/src/api/leaderboardAPI.ts
  packages/client/src/components/BurgerMenu/BurgerMenu.tsx
  packages/client/src/config/constants.tsx
  packages/client/src/pages/ErrorPage/ErrorPage.tsx
  packages/client/src/pages/Leaderboard/DummyData.ts
  packages/client/src/pages/Leaderboard/Leaderboard.css
  packages/client/src/pages/Leaderboard/Leaderboard.test.tsx
  packages/client/src/pages/Leaderboard/Leaderboard.tsx
  packages/client/src/pages/Leaderboard/LeaderboardField/LeaderboardField.css
  packages/client/src/pages/Leaderboard/LeaderboardField/LeaderboardField.tsx
  packages/client/src/pages/Leaderboard/LeaderboardField/SortMarker/SortMarker.css
  packages/client/src/pages/Leaderboard/LeaderboardField/SortMarker/SortMarker.tsx
  packages/client/src/pages/Leaderboard/LeaderboardField/SortMarker/typings.ts
  packages/client/src/pages/Leaderboard/LeaderboardField/typings.ts
  packages/client/src/pages/Leaderboard/LeaderboardRow/LeaderboardRow.css
  packages/client/src/pages/Leaderboard/LeaderboardRow/LeaderboardRow.test.tsx
  packages/client/src/pages/Leaderboard/LeaderboardRow/LeaderboardRow.tsx
  packages/client/src/pages/Leaderboard/LeaderboardRow/typings.ts
  packages/client/src/pages/Leaderboard/data.ts
  packages/client/src/pages/Leaderboard/typings.ts
  packages/client/src/store/features/leaderboard/leaderboardSlice.ts
  packages/client/src/store/features/leaderboard/leaderboardThunks.ts
  packages/client/src/store/features/leaderboard/typings.ts
  packages/client/src/store/index.ts
  packages/client/src/store/store.ts
  packages/client/src/utils/dateUtils.ts
  yarn.lock
Labels: enhancement

#67 Add meta tags
  packages/client/index.html
  packages/client/package.json
  packages/client/src/config/constants.tsx
  packages/client/src/game/entities/Explosion.test.ts
  packages/client/src/game/entities/Score.test.ts
  packages/client/src/game/entities/Score.ts
  packages/client/src/game/entities/TankEnemy.ts
  packages/client/src/game/entities/TankPlayer.test.ts
  packages/client/src/game/services/Game.ts
  packages/client/src/game/services/Statistics.test.ts
  packages/client/src/game/services/Statistics.ts
  packages/client/src/game/ui/Overlay.ts
  packages/client/src/game/ui/screens/index.ts
  packages/client/src/pages/ErrorPage/ErrorPage.tsx
  packages/client/src/pages/Forum/Forum.tsx
  packages/client/src/pages/Forum/ForumSection/ForumSection.tsx
  packages/client/src/pages/Forum/ForumTopic/ForumTopic.tsx
  packages/client/src/pages/Game/Game.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/pages/Leaderboard/Leaderboard.tsx
  packages/client/src/pages/Leaderboard/LeaderboardField/SortMarker/SortMarker.css
  packages/client/src/pages/SignIn/SignIn.tsx
  packages/client/src/pages/SignUp/SignUp.tsx
  packages/client/src/pages/UserProfile/UserProfile.tsx
  packages/client/src/utils/seoUtils.tsx
  packages/server/index.ts
  packages/server/package.json
  yarn.lock
Labels: enhancement

#68 Add oauth
  .env.sample
  packages/client/jest.config.js
  packages/client/src/api/oauthAPI.ts
  packages/client/src/components/Form/Form.css
  packages/client/src/config/constants.tsx
  packages/client/src/config/router.tsx
  packages/client/src/layouts/Root/Root.tsx
  packages/client/src/pages/SignIn/SignIn.tsx
  packages/client/src/store/features/oauth/oauthThunks.ts
  packages/client/src/store/index.ts
  packages/client/vite.config.ts
  packages/server/index.ts
Labels: enhancement

#71 Update game engine description
  docs/gameEngine.md
  packages/client/src/game/entities/Entity.ts
  packages/client/src/game/entities/EntityDynamic.ts
  packages/client/src/game/entities/Tank.ts
Labels: documentation

#73 Add http-proxy-middleware
  packages/client/src/api/authAPI.ts
  packages/client/src/api/leaderboardAPI.ts
  packages/client/src/api/oauthAPI.ts
  packages/client/src/api/userAPI.ts
  packages/client/src/config/constants.tsx
  packages/client/src/pages/UserProfile/UserProfile.tsx
  packages/client/src/tests/setup.ts
  packages/client/src/utils/HTTP/HTTP.tsx
  packages/client/src/utils/HTTP/determineAPIHost.ts
  packages/client/src/utils/HTTP/index.tsx
  packages/server/index.ts
  packages/server/package.json
  yarn.lock
Labels: enhancement

#74 Docker and Postgres configuration
  .env.sample
  Dockerfile.client
  Dockerfile.server
  README.md
  docker-compose.yml
  init.js
  package.json
  packages/server/api/services/ForumSection.ts
  packages/server/db.ts
  packages/server/index.ts
  packages/server/models/ForumSection.ts
  packages/server/package.json
  packages/server/routes/Api.ts
  packages/server/tsconfig.json
  yarn.lock
Labels: enhancement

#79 Show menu items based on user auth status
  packages/client/src/components/BurgerMenu/BurgerMenu.test.tsx
  packages/client/src/components/MenuLink/typings.ts
  packages/client/src/components/Navigation/Navigation.tsx
  packages/client/src/components/Navigation/data.ts
  packages/client/src/components/Navigation/typings.ts
  packages/client/src/components/ProtectedRoutes/ProtectedRoutes.tsx
  packages/client/src/pages/Home/Home.test.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/utils/navigationUtils.ts
  packages/server/routes/Api.ts
Labels: enhancement

#82 Add contact form
  .env.sample
  docker-compose.yml
  docs/lerna/README.md
  init.d/app-init.js
  init.d/mongo-init.sh
  package.json
  packages/client/jest.config.js
  packages/client/src/api/contactAPI.ts
  packages/client/src/client.d.ts
  packages/client/src/components/Form/FieldList/Field/Field.tsx
  packages/client/src/components/Form/FieldList/Field/typings.tsx
  packages/client/src/components/Form/FieldList/FieldList.tsx
  packages/client/src/components/Navigation/data.ts
  packages/client/src/config/constants.tsx
  packages/client/src/config/router.tsx
  packages/client/src/pages/Contact/Contact.test.tsx
  packages/client/src/pages/Contact/Contact.tsx
  packages/client/src/pages/Contact/data.ts
  packages/client/src/pages/Contact/index.ts
  packages/client/src/pages/Contact/typings.tsx
  packages/client/src/utils/HTTP/HTTP.tsx
  packages/client/src/utils/navigationUtils.ts
  packages/client/vite.config.ts
  packages/server/api/services/Contact.ts
  packages/server/db.ts
  packages/server/index.ts
  packages/server/middlewares/bodyParser.ts
  packages/server/middlewares/cors.ts
  packages/server/middlewares/index.ts
  packages/server/middlewares/proxy.ts
  packages/server/mongoModels/Contact.ts
  packages/server/package.json
  packages/server/routes/Api.ts
  packages/server/utils/databaseUtils.ts
  yarn.lock
Labels: enhancement

#81 Add enemy tank variants
  packages/client/src/game/entities/Entity/Entity.ts
  packages/client/src/game/entities/Tank/Tank.ts
  packages/client/src/game/entities/Tank/TankEnemy.ts
  packages/client/src/game/entities/Tank/typings.ts
  packages/client/src/game/services/AudioManager/AudioManager.ts
  packages/client/src/game/services/MapManager/MapManager.ts
  packages/client/src/game/services/MapManager/enemyForces.ts
  packages/client/src/game/services/MapManager/levels.ts
  packages/client/src/game/services/MapManager/typings.ts
  packages/client/src/game/services/Scenario/Scenario.ts
  packages/client/src/game/services/Scenario/typings.ts
Labels: enhancement

#83 Add themization
  README.md
  packages/client/index.html
  packages/client/public/assets/favicon/site.webmanifest
  packages/client/src/api/themizationAPI.ts
  packages/client/src/components/Breadcrumbs/Breadcrumbs.css
  packages/client/src/components/BurgerMenu/BurgerMenu.css
  packages/client/src/components/BurgerMenu/BurgerMenu.tsx
  packages/client/src/components/Button/Button.css
  packages/client/src/components/Dropdown/Dropdown.css
  packages/client/src/components/Footer/Footer.css
  packages/client/src/components/Form/Form.css
  packages/client/src/components/Loader/Loader.css
  packages/client/src/components/Logo/Logo.css
  packages/client/src/components/Logo/Logo.tsx
  packages/client/src/components/MenuLink/MenuLink.css
  packages/client/src/components/MenuLink/MenuLink.tsx
  packages/client/src/components/ThemeToggle/ThemeToggle.css
  packages/client/src/components/ThemeToggle/ThemeToggle.test.tsx
  packages/client/src/components/ThemeToggle/ThemeToggle.tsx
  packages/client/src/components/ThemeToggle/data.ts
  packages/client/src/components/ThemeToggle/index.tsx
  packages/client/src/components/ThemeToggle/typings.ts
  packages/client/src/components/ValidationErrors/ValidationErrors.css
  packages/client/src/config/constants.tsx
  packages/client/src/game/services/MapManager/MapManager.ts
  packages/client/src/index.css
  packages/client/src/layouts/Root/Root.css
  packages/client/src/pages/ErrorPage/ErrorPage.css
  packages/client/src/pages/Forum/Forum.css
  packages/client/src/pages/Forum/ForumTopic/ForumMessage/ForumMessage.css
  packages/client/src/pages/Forum/ForumTopic/ForumTopic.css
  packages/client/src/pages/Home/Home.css
  packages/client/src/pages/Leaderboard/Leaderboard.css
  packages/client/src/pages/Leaderboard/LeaderboardRow/LeaderboardRow.css
  packages/client/src/tests/setup.ts
  packages/client/src/variables.css
  packages/server/api/services/Themization.ts
  packages/server/config/constants.ts
  packages/server/index.ts
  packages/server/middlewares/checkAuth.ts
  packages/server/middlewares/index.ts
  packages/server/middlewares/proxy.ts
  packages/server/models/Themes.ts
  packages/server/models/UserThemes.ts
  packages/server/routes/Api.ts
  packages/server/utils/databaseUtils.ts
Labels: enhancement

#84 Fix game bugs
  packages/client/src/api/leaderboardAPI.ts
  packages/client/src/game/entities/Entity/Entity.ts
  packages/client/src/game/entities/Projectile/Projectile.ts
  packages/client/src/game/entities/Tank/TankPlayer.test.ts
  packages/client/src/game/services/Controller/KeyBindings.ts
  packages/client/src/game/services/Game/Game.ts
  packages/client/src/game/services/IndicatorManager/IndicatorManager.test.ts
  packages/client/src/game/services/Loop/Loop.ts
  packages/client/src/game/services/Scenario/Scenario.test.ts
  packages/client/src/game/services/Scenario/Scenario.ts
  packages/client/src/game/services/Scenario/typings.ts
  packages/client/src/game/services/Statistics/Statistics.test.ts
  packages/client/src/game/services/Statistics/Statistics.ts
  packages/client/src/game/services/Zone/Zone.test.ts
  packages/client/src/game/services/Zone/Zone.ts
  packages/client/src/store/features/leaderboard/leaderboardSlice.ts
Labels: bug
